### PR TITLE
Workaround for android chat log format

### PR DESCRIPTION
**Pull request by kittinan**
## Workaround for android chat log format

- Android chat log start like below

```
﻿Chat history with NAME
Saved on: 2017/09/05 12:12

2017/03/12(Sun)
```

- Android time format use 24:XX instead of 00:XX

### CODE REVIEW

**Comment by titipata** [comment]
Thank you so much @kittinan!

**Comment by bluenex** [comment]
Does the time format depend on OS rather than system settings?

**Comment by titipata** [comment]
It depends on where you export it from. I think if you export directly from Android phone, it's different from exporting from Line from desktop.

**Comment by kittinan** [comment]
@bluenex not sure

**Pull request merged**
